# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 13:34
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('details', models.TextField(null=True)),
                ('bid_res', models.DateTimeField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('active', models.IntegerField()),
                ('banned', models.BooleanField(default=False)),
                ('last_bid', models.DecimalField(decimal_places=2, default=0.01, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('last_bider', models.TextField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bid', models.DecimalField(decimal_places=2, default=0.01, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Auction')),
                ('bid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
