# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20171112_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='last_bider',
            field=models.TextField(null=True),
        ),
    ]
