# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20171004_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='auction',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='published_date',
        ),
        migrations.AddField(
            model_name='auction',
            name='bid_res',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='auction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 23, 8, 49, 974428)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='bid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='details',
            field=models.TextField(),
        ),
    ]
