# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0004_auto_20171004_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 6, 13, 4, 30, 147883), null=True),
        ),
    ]
