# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_auto_20171006_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='author',
            new_name='user',
        ),
    ]
