# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_auto_20171006_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='user',
        ),
    ]
