# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0009_remove_auction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
