# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_auto_20171006_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
