# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0012_auto_20171006_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
