# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0013_auction_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid_res',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
