# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 19:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0014_auto_20171008_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid_res',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 8, 19, 26, 20, 657481), null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 8, 19, 26, 20, 657514), null=True),
        ),
    ]
