# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0015_auto_20171008_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='bid_res',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 16, 58, 31, 882322), null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 16, 58, 31, 882351), null=True),
        ),
    ]
