# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_auto_20171009_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='active',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='bid_res',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 17, 14, 8, 861892), null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 17, 14, 8, 861922), null=True),
        ),
    ]
