# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0017_auto_20171009_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid_res',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 17, 47, 34, 195901), null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 17, 47, 34, 195942), null=True),
        ),
    ]
