# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0018_auto_20171009_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid_res',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='timestamp',
            field=models.DateField(null=True),
        ),
    ]
