# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0021_auction_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('bid', models.DecimalField(decimal_places=1, max_digits=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default=b'en', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='auction',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='bid_by',
        ),
        migrations.AddField(
            model_name='bids',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Auction'),
        ),
        migrations.AddField(
            model_name='bids',
            name='bid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
