# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0023_auto_20171107_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_profile',
        ),
    ]
