# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0024_auto_20171107_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.DecimalField(decimal_places=1, default=0.01, max_digits=10),
        ),
    ]
